### ISSUE TITLE
Help...

### ISSUE THREAD

**Issue by DestroyTargetNonBasicLand** [Catgrills/Nightingale#3]
When clicking images this happens:
![help](https://user-images.githubusercontent.com/36361031/84634308-2469a780-aee1-11ea-90b1-642a6a649944.PNG)

Thanks you kindly.
Big fan of your work by the way!

**Comment by Catgrills** [comment]
Hello Destroy,

Sorry for the late reply, going to solve it asap.

**Comment by DestroyTargetNo** [comment]
Perfect! It's all fixed and works like a charm, thank you so much!

**Comment by DestroyTargetNo** [comment]
Oops, completely forgot to report this issue as well.. My apologies.

![nZ0lmFYl09](https://user-images.githubusercontent.com/36361031/85215415-d3860300-b367-11ea-906e-a4298b0d68b4.gif)

**Comment by Catgrills** [comment]
Hello,

Sorry for the late reply, I've updated the script. Don't hesitate to report others issues with the script.

**Comment by DestroyTargetNonBasicLand** [comment]
No worries! I just hope you're doing well in these trying time..

Anyways,
Beside the ones below I think all the major issues have been solved so far. 
![ae](https://user-images.githubusercontent.com/36361031/87420815-73c8f380-c5c5-11ea-95f9-ee9b74d18bba.PNG)
![ea](https://user-images.githubusercontent.com/36361031/87421562-a7584d80-c5c6-11ea-89ce-bc25bdf00fdf.PNG)

**Comment by DestroyTargetNonBasicLand** [comment]
New theme looks pretty neato, well done.
