### ISSUE TITLE
Does it work still?

### ISSUE THREAD

**Issue by kasdeya** [Catgrills/Nightingale#4]
It doesn't seem to work for me.

**Comment by Catgrills** [comment]
Hello kasdeya,

Sorry for the late reply. Normally, the script should work. Can you send a screenshot of twitter with the script activated ?

**Comment by kasdeya** [comment]
[https://puu.sh/GVO4M/8ada7dab55.png](url)

**Comment by Catgrills** [comment]
Oh yeah, I forgot to update the preview : twitter design changed, so I decided to change the layout, that's why it's different from the preview.

**Comment by kasdeya** [comment]
i see, love ur work/style!
Thanks.
